Assignment 2
sunshinesharon/python pull request #2
Opened 2024-12-09 04:07 UTC by sunshinesharon

## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
I've added code to analyze the inflammation dataset per requirements of Assignment 2. This includes reading data, summarizing patient inflammation statistics, and detecting irregularities.

## What did you learn from the changes you have made?
I learned how to work with CSV files, calculate summary statistics using NumPy, and implement error detection for datasets. The assignment also helped me understand the importance of testing and verifying file paths.

## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
None, as this is very new to me. 

## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
One of the challenges I faced was setting up the correct relative paths for the data files. I resolved it by debugging the file paths using 'os.getcwd()'  to ensure the all_paths were accurate.

## How were these changes tested?
I tested the changes by running the notebook and verifying that the outputs matched the expected results, such as ensuring arrays had 60 elements and checking for error detection accuracy.

## A reference to a related issue in your repository (if applicable)
NA 

## Checklist
- [x] Ensure the notebook executes without any errors.
- [x] Check that all three tasks (Task 1, Task 2, Task 3) are implemented and tested.
- [x] Verify paths (all_paths) are correct for your folder structure.
- [x] Confirm that the repository is public and accessible.

2024-12-09 16:28 UTC, pedram-aliniaye-asli commented
you did a great job here!
Part 2, needs to be modified as it returns nothing or `None` when the `is_case_sensitive` is True. You can work on its indentation. 
Please go ahead and do the modifications and then let me know. Thanks!

2024-12-10 23:22 UTC, anjali-deshpande-hub requested changes
Well done with the assignment!
I see changes to assignment-1.ipynb in this PR as well. There should only be assignment_2.ipynb changes in this PR. Please make the correction. Everything else looks good!

2024-12-13 04:53 UTC, anjali-deshpande-hub commented
In order to fix the problem of changes in assignment_1.ipynb in assignment_2 branch, follow the steps listed in thread https://uoft-dsi-certificates.slack.com/archives/C07VC7M4PTL/p1733888327768759

2024-12-16 15:37 UTC, anjali-deshpande-hub approved these changes
For future, please update your branch with the latest changes from the main (or master) branch before making a pull request (PR). That way your branch is aligned with the most recent version of the project and your PR will only contain the code that is to be reviewed and merged.
This PR contains both assignment_1.ipynb and assignment_2.ipynb file changes and should only contain assignment_2.ipynb file changes. Thank you.

2025-01-13 03:18 UTC, merged